config/routes.rb
Enex::Application.routes.draw do
 resources :users
 resources :experts
 resources :sessions, only: [:new, :create, :destroy ]
  
  match '/login',     to: 'sessions#new'
  match '/logout',    to: 'sessions#destroy', via: :delete
  
  match '/contact',   to: 'static_pages#contact'
  match '/impressum', to: 'static_pages#impressum'
  match '/eausweis',  to: 'experts#eausweis'
  match '/eberatung', to: 'experts#eberatung'
  match '/list_exp_ea', to: 'experts#show_experts_ea'
  root                :to => 'static_pages#home'

end

app/views/layouts/_dummy.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-xs-4 col-md-3">
			<!--Sidebar content-->
			<ul>
			<li>jajajajjajajajja</li>
			<li>jajajajjajajajja</li>
			<li>jajajajjajajajja</li>
			<li>jajajajjajajajja</li>
			</ul><li>
		</div>
		<div class="col-xs-14 col-sm-6 col-md-9">
			<!--Body content-->
			<p>Freilebende Gummibärchen gibt es nicht. Man kauft sie in Packungen an der Kinokasse. 
			Dieser Kauf ist der Beginn einer fast erotischen und sehr ambivalenten Beziehung Gummibärchen-Mensch. 
			Zuerst genießt man. Dieser Genuß umfaßt alle Sinne. Man wühlt in den Gummibärchen, man fühlt sie. 
			Gummibärchen haben eine Konsistenz wie weichgekochter Radiergummi. Die Tastempfindung geht auch 
			ins Sexuelle. Das bedeutet nicht unbedingt, daß das Verhältnis zum Gummibärchen ein geschlechtliches wäre, 
			denn prinzipiell sind diese geschlechtsneutral. Nun sind Gummibärchen weder wabbelig noch zäh; 
			sie stehen genau an der Grenze. </p>
		</div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
	<div class="col-md-12 col-lg-10">
			<footer class="abgerundet">
				
					&copy;&nbsp;2014&nbsp;<a href="http://www.die-energieberatungsagentur.de" target="_blank">Energieberatungsagentur Nord</a>
					<span style='float: right;'><%= link_to 'Kontakt', '/contact' %>&nbsp;&bull;&nbsp;<%= link_to 'Impressum', '/impressum' %></span>
				
			</footer>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 col-lg-10 thumbnail">		
	    <%= link_to (image_tag '/assets/enex-header940x150.png') , '/' %>
		</div>
	</div>
</div>

app/views/layouts/_intern.html.erb
<div class="menue">
	<ul>
		<% if session[:request] == 'login' %>
			<li>
				<%= link_to 'Startseite', '/' %>
			</li>
		<% end %>
		<% if signed_in? %>
			<li>
				<%= link_to "Logout", '/logout', method: "delete" %>
			</li>
		<% end %>
	</ul>
</div>

app/views/layouts/_menue.html.erb
<div class="menue">
	<ul>
		<% if !signed_in? %>
			<% if session[:request] == '' %>
				<li>
					<%= link_to "Energieausweis erstellen", '/eausweis' %>
				</li>
				<li>
					<%= link_to "Energieberatung durchfuehren", '/eberatung' %>
				</li>
			<% end %>		
			<% if session[:request] == 'eausweis' %>
				<li>
					<img src="/assets/icon-eausweis-blau100x100.png" width="100" heigth="100" title="Energieausweis erstellen">
				</li>
				<li>
					<%= link_to 'Energieberatung durchfuehren', '/eberatung' %>
				</li>
			<% end %>
			<% if session[:request] == 'eberatung' %>
				<li>
					<img src="/assets/icon-eberatung-blau100x100.png" width="100" heigth="100" title="Energieberatung durchf&uuml;hren">
				</li>
				<li>
					<%= link_to 'Energieausweis erstellen', '/eausweis' %>
				</li>
			<% end %>
			<% if session[:request] == '' %>
				<li>
					<a  href="#">Energieportal</a>
				</li>
				<p>&nbsp;</p>
			<% end %>
		<% end %>
		<% if !signed_in? && session[:request] != 'login' %>		
			<li>
				<%= link_to "Login", '/login' %>
			</li>
		<% end %>
		<% if !signed_in? && session[:request] == 'login' %>
			<li>
				<%= link_to "Startseite", '/' %>
			</li>
		<% end %>
		<% if signed_in? and session[:request] == 'experts' %>
			<li>
				<%= link_to "Home", root_path %>
			</li>

			<li>
				<%= link_to "Logout", '/logout', method: "delete" %>
			</li>
		<% end %>
		<% if signed_in? &&  session[:request] == 'new_expert' %>
			<li>
				<%= link_to 'Abbrechen', experts_path %>
			</li>
			<li>
				<%= link_to "Logout", '/logout', method: "delete" %>
			</li>
		<% end %>
		<% if signed_in? and session[:request] == '' %>
			<li>
				<%= link_to "Expertendaten", experts_path %>
			</li>
			<li>
				<%= link_to "Logout", '/logout', method: "delete" %>
			</li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
	<head>
		<title>EnEx - Die Energie-Experten-Suche</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="revisit-after" content="3 days" />
		<meta name="description" content="EnEx - Die Energie-Experten-Suche" />
		<meta name="keywords" content="Energieberatung Salzgitter, Energieberatungsagentur, Energieberatung, Energieausweis, Salzgitter, Lebenstedt, Salzgitter-Bad, Wolfenbüttel, Braunschweig, Peine, Energieeffizienz, Energieverbrauch, Energiebedarf, kfw-förderung, KfW, Förderprogramm, Mittelstand, KMU, Freiberufler, Selbstständige, kleine und mittlere Unernehmen, unabhängig, Initialberatung, Energieberater, Klima schützen, Kosten senken, Imagesteigerung, Verbrauch optimieren, DEN, Deutsches Energieberater Netzwerk, BAFA, dena, die-energieberatungsagentur.de, www.die-energieberatungsagentur.de, UR" />
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-lg-2">
					<%= render 'layouts/menue' %>
				</div>
				<div class="col-md-10 col-lg-8">
					<% flash.each do |key, value| %>
						<%= content_tag(:div, value, class: "alert alert-#{key}") %>
					<% end %>
					<%= yield %>
				</div>
			</div>	
			<%= render 'layouts/footer' %>
		</div>
		<%= debug(params) if Rails.env.development? %>
		<% debug(params[:page]) if Rails.env.development? %>
	</body>
</html>