config/routes.rb
Enex::Application.routes.draw do
 resources :users
 resources :experts
 resources :sessions, only: [:new, :create, :destroy ]
  
  match '/login',     to: 'sessions#new'
  match '/logout',    to: 'sessions#destroy', via: :delete
  
  match '/contact',   to: 'static_pages#contact'
  match '/impressum', to: 'static_pages#impressum'
  match '/eausweis',  to: 'experts#eausweis'
  match '/eberatung', to: 'experts#eberatung'
  match '/list_exp_ea', to: 'experts#show_experts_ea'
  root                :to => 'static_pages#home'

end

app/models/expert.rb
class Expert < ActiveRecord::Base
   attr_accessible :firmenname, :anrede, :titel, :name, :vorname, :strasse, :hausnr, :plz_7, :plz, 
				:ort, :vorwahl, :telefon, :email, :website, :ausbildung, 
				:bafa, :kfw_bauen_und_sanieren, :energ_fachplanung, :baubegleitung, 
				:kfw_denkmal

   	before_save { |expert| expert.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :new, :update, :create, :destroy]
  
  # GET /experts
  # GET /experts.json
  def eausweis
	store_request('eausweis')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experts }
    end
  end

  def eberatung
	store_request('eberatung')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experts }
    end
  end
  
	
  # GET /show_experts_ea Suchergebnis Energieexperten
  def show_experts_ea
    @objart = params[:optobjektart]
	@postlz = params[:plz]
	@radius = params[:kmradius]
	
	musterplz = /^\d{5}$/
	respond_to do |format|
		if !@postlz.empty? && @postlz =~ musterplz
			# Lokationsdaten der eingebenen PLZ selektieren
			@plzloc = GeodbPlzLoc.where("plz = :plz", plz: @postlz)
			if !@plzloc.empty? 
				splz = @plzloc[0]
				@experts = Expert.find_by_sql( " SELECT ACOS(SIN(" + splz.lat_bm.to_s + ") * SIN(lat_bm) + " +
								"COS(" + splz.lat_bm.to_s + ") * COS(lat_bm) * COS(" + splz.lon_bm.to_s + " - lon_bm)) * 6380 " +
								"AS distance, experts.* FROM geodb_plz_locs , experts " + 
								"where geodb_plz_locs.plz_7 = experts.plz_7 " +
								"HAVING distance <='" + @radius + "'").paginate(:page => params[:page], :per_page => 8)
				
				#@experts = Expert.where("plz = :plz and objekt_art = :objektart", 
				#		plz: splz.plz, objektart: @objart)
				format.html # show_experts_ea.html.erb
				#format.csv { render text: @experts.to_csv }
				#format.json { render json: @expert }
			else
				flash.now[:warning] = "Die eingegebene PLZ wurde nicht gefunden!"
				format.html { render action: "eausweis" }
			end	
		else
			flash.now[:warning] = "Bitte eine 5-stellige PLZ eingeben!"
			format.html { render action: "eausweis" }
		end
	end
  end	
  
  
  # GET /experts
    def index
		store_request('experts')
		pager = session[:page] ||= params[:page]
		store_page pager
		sort = 'plz'
		@experts = Expert.find(:all, :order => sort).paginate(page: pager, per_page: 15)
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @experts }
		end
	end
	
  	def edit
		store_request('new_expert')
		read_last_page
		@expert = Expert.find(params[:id])
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @experts }
		end
	end
	# 
	def new
		store_request('new_expert')
		@expert = Expert.new
		read_last_page
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @experts }
		end
	end

  # POST /experts
  # POST /experts.json
	def create
		@expert = Expert.new(params[:expert])
		@expert.created_by = current_user.email
		#read_last_page
		respond_to do |format|
		if @expert.save
			flash[:success] = 'Der Experte wurde gespeichert.'
			format.html { redirect_to experts_path }
			format.json { render json: @expert, status: :created, location: @expert }
		else
			format.html { render action: "new"}
			format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experts/1
  # PUT /experts/1.json
  def update
    @expert = Expert.find(params[:id])
	@expert.update_by = current_user.email
    respond_to do |format|
      if @expert.update_attributes(params[:expert])
		flash[:success] = 'Daten wurden gespeichert.'
        format.html { redirect_to experts_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experts/1
  # DELETE /experts/1.json
  def destroy
    read_last_page
	@expert = Expert.find(params[:id])
    @expert.destroy
	flash[:success] = 'Daten wurden geloescht!'
    respond_to do |format|
      format.html { redirect_to experts_url }
      format.json { head :no_content }
    end
  end
  
  private
  	
	def store_request(req)
		session[:request] = req
	end 
			
end

app/helpers/experts_helper.rb
module ExpertsHelper
	
end

app/views/experts/_form.html.erb
<%= form_for(@expert, class: 'form-horizontal') do |f| %>
  <% if @expert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expert.errors.count, "error") %> prohibited this expert from being saved:</h2>

      <ul>
      <% @expert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	</div>
	<% end %>
	<div class="row">
		<div class="form-group">
			<label for="firmenname" class="col-sm-2 control-label">Firma</label>
			<div class="col-sm-6">
				<%= f.text_field :firmenname, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="Anrede" class="col-sm-2 control-label">Anrede</label>
			<div class="col-sm-2">
				<%= f.text_field :anrede, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="titel" class="col-sm-2 control-label">Titel</label>
			<div class="col-sm-2">
				<%= f.text_field :titel, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="Name" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-6">
				<%= f.text_field :name, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="Strasse" class="col-sm-2 control-label">Stra&szlig;e/HausNr</label>
			<div class="col-sm-6">
				<%= f.text_field :strasse, class: 'form-control' %>
			</div>
			<div class="col-sm-2">
				<%= f.text_field :hausnr, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="control-group">
			<label for="plz" class="col-sm-2 control-label">PLZ</label>
			<div class="col-sm-2">
				<%= f.text_field :plz, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="control-group">
			<label for="Ort" class="col-sm-2 control-label">Ort</label>
			<div class="col-sm-6">
				<%= f.text_field :ort, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="Vorwahl" class="col-sm-2 control-label">Vorwahl/Telefon</label>
			<div class="col-sm-2">
				<%= f.text_field :vorwahl, class: 'form-control' %>
			</div>
			<div class="col-sm-2">
				<%= f.text_field :telefon, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="Email" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-4">
				<%= f.text_field :email, class: 'form-control', type: 'email' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="webseite" class="col-sm-2 control-label">Website</label>
			<div class="col-sm-4">
				<%= f.text_field :website, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="ausbildung" class="col-sm-2 control-label">Ausbildung</label>
			<div class="col-sm-6">
				<%= f.text_field :ausbildung, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="bafa" class="col-sm-2 control-label">BaFa</label>
			<div class="col-sm-1">
				<%= f.check_box :bafa, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="kfw_b" class="col-sm-2 control-label">KfW-Bau</label>
			<div class="col-sm-1">
				<%= f.check_box :kfw_bauen_und_sanieren, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->		
	<div class="row">
		<div class="form-group">
			<label for="ef" class="col-sm-2 control-label">energ.Fachplan.</label>
			<div class="col-sm-1">
				<%= f.check_box :energ_fachplanung, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">
		<div class="form-group">
			<label for="baubegleitung" class="col-sm-2 control-label">Baubegleitung</label>
			<div class="col-sm-1">
				<%= f.check_box :baubegleitung, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->
	<div class="row">	
		<div class="form-group">
			<label for="kfw_denkmal" class="col-sm-2 control-label">KfW_Denkmal</label>
			<div class="col-sm-1">
				<%= f.check_box :kfw_denkmal, class: 'form-control' %>
			</div>
		</div>
	</div><!-- /row -->	
	<br />
	<div class="row">
		<div class="form-group">
			<div class="col-sm-2">
				<%= f.submit "speichern", class: "btn btn-sm btn-primary" %>
			</div>
		</div>
	</div><!-- /row -->		
<% end %>

app/views/experts/eausweis.html.erb
<div class="content">
	<h3>Energieausweis</h3>
	<p>Wof&uuml;r soll der Energieausweis erstellt werden?</p>
	<%= form_tag('/list_exp_ea', method: :get) do %>
		<form class="form-horizontal" role="form">
			<div class="form-group">
				<div class="radio">
				  <label>
					<input type="radio" name="optobjektart" id="optionsRadios1" value="WG" checked>
					Wohngeb&auml;ude
				  </label>
				</div>
				<div class="radio">
				  <label>
					<input type="radio" name="optobjektart" id="optionsRadios2" value="NWG">
					Nicht-Wohngeb&auml;ude
				  </label>
				</div>
			</div>
			<p><button type="button" class="btn btn-default" data-toggle="collapse" data-target="#demo">
				weitere Optionen</button></p>				
				<div id="demo" class="collapse">
					<div class="form-group">
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="thermografie" id="optchkbox1" value="tg" >
							Thermografie
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="bdt" id="optchkbox2" value="bdt" >
							Luftdichtigkeitspr&uuml;fung/Blower Door Test
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="ssb" id="optchkbox3" value="ssb" >
							Stromsparberatung
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="ecno" id="optchkbox4" value="ecno" >
							Energiechecks (nicht online)
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="eco" id="optchkbox5" value="eco" >
							Energiechecks (online)
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="seb" id="optchkbox6" value="seb" >
							Sonstige Energieberatung
						  </label>
						</div>						
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="erek" id="optchkbox7" value="erek" >
							Erstellung und Realisierung von Energiekonzepten
						  </label>
						</div>						
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="gm" id="optchkbox8" value="gm" >
							Geb&auml;udemodernisierung
						  </label>
						</div>						
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="ium" id="optchkbox9" value="ium" >
							Informations- und Motivationsma&szlig;nahmen
						  </label>
						</div>
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="pum" id="optchkbox10" value="pum" >
							Projektunterst&uuml;tzende Ma&szlig;nahmen
						  </label>
						</div>						
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="vob" id="optchkbox11" value="vobm" >
							Vor-Ort-Beratung (BAFA)
						  </label>
						</div>						
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="ee" id="optchkbox12" value="ee" >
							EE Bauen und Sanieren
						  </label>
						</div>					
						<div class="checkbox">
						  <label>
							<input type="checkbox" name="fub" id="optchkbox13" value="fub" >
							Fachplanung und Baubegleitung  &quot;Energieeffizient Sanieren&quot;
						  </label>
						</div>											
					</div><!-- /form-group -->
				</div><!-- /demo -->
			<p>Aus welchem Umkreis soll der Energie-Experte kommen ?</p>
			<div class="form-group inline">
				<input type="text" class="text-inline" placeholder="PLZ" name="plz">
				<input type="radio" class="checkBox" name="kmradius" id="kmradius1" value="20" checked> 20 km
				<input type="radio" class="checkBox" name="kmradius" id="kmradius2" value="50"> 50 km
				<input type="radio" class="checkBox" name="kmradius" id="kmradius3" value="100"> 100 km
				<input type="radio" class="checkBox" name="kmradius" id="kmradius4" value="101"> >100 km
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Suche starten</button>
			</div>


		</form>
	<% end %>
</div>
<script language="javascript" type="text/javascript">
<!--
$(document).ready(function()
{
    $(".checkBox,.checkBoxClear").click(function(srcc)
    {
        if ($(this).hasClass("checkBox"))
        {
            $(this).removeClass("checkBox");
            $(this).addClass("checkBoxClear");
        }
        else
        {
            $(this).removeClass("checkBoxClear");
            $(this).addClass("checkBox");
        }
    });        
});
//-->
</script>

app/views/experts/eberatung.html.erb
<div class="content">
<h3>Energieberatung</h3>

</div>

app/views/experts/edit.html.erb
<div class="row">
	<h3>Expertendaten bearbeiten</h3>
	<%= render 'form' %>
</div><!-- /row -->	

app/views/experts/index.html.erb
<div class="row">
	<div class="col-md-10 col-lg-8">
		<h3>Liste der Energie-Experten</h3>
		<%= link_to "Neuer Experte", new_expert_path %>
	</div>
</div><!-- /row -->
<div class="row">
	<div class="col-md-10 col-lg-8">
		<div class="pagination">
			<%= will_paginate @experts, :previous_label => "&laquo; Zur&uuml;ck", :next_label => " Vor &raquo;" %>
		</div>
	</div>
</div><!-- /row -->
<div class="row">
	<div class="col-md-10 col-lg-8">
		<table class="table-condensed table-hover" >
		  <tr>
			<th>Firma/Name</th>
			<th>EMail</th>
			<th>Plz</th>
			<th>Ort</th>
		  </tr>
		<% @experts.each do |expert| %>
		  <tr>
			<% if expert.firmenname.empty? %>
				<td><%= link_to expert.name, edit_expert_path(expert) %></td>
			<% else %> 
				<td><%= link_to expert.firmenname, edit_expert_path(expert) %></td>
			<% end %>
			<td><%= expert.email %></td>
			<td><%= expert.plz %></td>
			<td><%= expert.ort %></td>
		  </tr>
		<% end %>
		</table>
	<div>
</div><!-- /row -->
<div class="row">
	<div class="col-md-10 col-lg-8">
		<div class="pagination">
			<%= will_paginate @experts, :previous_label => "&laquo; Zur&uuml;ck", :next_label => " Vor &raquo;" %>
		</div>
	</div>
</div><!-- /row -->

app/views/experts/index_orig.html.erb
<h1>Listing experts</h1>

<table>
  <tr>
    <th>Firma</th>
    <th>Plz</th>
    <th>Ort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experts.each do |expert| %>
  <tr>
    <td><%= expert.firma %></td>
    <td><%= expert.plz %></td>
    <td><%= expert.ort %></td>
    <td><%= link_to 'Show', expert %></td>
    <td><%= link_to 'Edit', edit_expert_path(expert) %></td>
    <td><%= link_to 'Destroy', expert, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expert', new_expert_path %>

app/views/experts/new.html.erb
<h3>Neuer Experte</h3>
<%= render 'form' %>

app/views/experts/show.html.erb
<h1>Expertendaten bearbeiten</h1>
<%= render 'form' %>

<%= link_to 'Back', experts_path %>

app/views/experts/show_experts_ea.html.erb
<div class="content">
	<h4>Ihre Suche:</h4>
	<ul>
		<li>PLZ: <%= @postlz %></li>
		<li>Objektart: <%= @objart %></li>
		<li>Radius: <%= @radius %>km</li>
	</ul>

	<div class="result">		
		<% if @experts.count > 0 %>
				<div class="pagination">
					ergab folgende Treffer: <%= will_paginate @experts, :previous_label => "&laquo; Zur&uuml;ck", :next_label => " Vor &raquo;" %>
				</div>
			<table class="table table-hover table-responsive">
				<thead>
					<tr>
						<th>Firma/Name</th>
						<th>PLZ</th>
						<th>Ort</th>
						<th>eMail</th>
					</tr>
				</thead>
				<tbody>
					<% @experts.each do |e| %>
						<tr>
							<% if e.firma.empty? %>
								<td><%= e.name %></td>
							<% else %> 
								<td><%= e.firma %></td>
							<% end %>
							<td><%= e.plz %></td>
							<td><%= e.ort %></td>
							<td><%= mail_to e.email %></td>
						</tr>
					<% end %>
				</tbody>
			</table>

		<% else %>
			<h5><span class="alert"> ergab leider keinen Treffer! </span></h5>
		<% end %>
	</div>	
	<%= button_to "Neue Suche", '/eausweis', :class => "btn btn-info" %>
	
</div>

 